### ISSUE TITLE
REQUEST - Remove black font outline

### ISSUE THREAD

**Issue by sasagr** [bkiziuk/service.subsmangler#19]
Kodi is still using a black outline in the subtitles font.
https://forum.kodi.tv/showthread.php?tid=337741

I m not sure if they will ever change it, for sure not in Matrix anyway.
Would it be interesting, doable to remove this ouline/border during conversion with this project?
In general I think the subtitles will have a more modern and better looking, see Netflix, Prime... on modern devices like the Apple TV for example.

**Comment by sasagr** [comment]
I tried to play with the ssastyle.py file in pysubs2 folder and change the "outline: float = 2.0" to 0.0 but it did not make any change.
Actually to test the changes in the file I also tried to modify the "underline" and "strikeout" to True but it did not change it so it looks like a simple edit of this file does not make a difference.
As I understand being the subtitles converted to ass there are many option available for changes in the way the font looks so I hope that this change I m looking for it is possible.
Thanks

**Comment by bkiziuk** [comment]
If you're using master branch, the pysubs2 library is called with the request to save subtitles in "srt" format:
[https://github.com/bkiziuk/service.subsmangler/blob/f3a64727f8eb50777c09d6ecdad4974d99da34d2/resources/lib/smangler.py#L754](url)

```
# save subs in a proper format
subs.save(tempoutputfile, format_="srt")
```
so unless you change an output format manually to Substation Alpha, the output file will not contain any font specific data.

For the previous version it was possible to adjust it from within the plugin:
[https://github.com/bkiziuk/service.subsmangler/blob/34bf3466fed3fc79cca538b93b2134a6e40ec346/resources/lib/smangler.py#L803](url)
```
    # change subs style
    subs.styles["Default"].primarycolor = pysubs2.Color(Foreground_R, Foreground_G, Foreground_B, 0)
    subs.styles["Default"].secondarycolor = pysubs2.Color(Foreground_R, Foreground_G, Foreground_B, 0)
    subs.styles["Default"].outlinecolor = pysubs2.Color(Background_R, Background_G, Background_B, Background_T)
    subs.styles["Default"].backcolor = pysubs2.Color(0, 0, 0, 0)
    subs.styles["Default"].fontsize = common.setting_SubsFontSize
    subs.styles["Default"].bold = -1
    subs.styles["Default"].borderstyle = 3
    subs.styles["Default"].shadow = 0
```
but this was dropped in 2.0.0 due to scaling issue with Substation Alpha format which I didn't like and also because Kodi 18 introduced solid background which is more readable.
The idea of 2.0.0 was to leave the font and background formatting to Kodi itself while processing only the subtitles content.

**Comment by sasagr** [comment]
I understand and hope that Kodi team would consider the possibility to change this settings because I m still convinced that it does not look nice to have the outline.
I understand it is not part of this project but if I want to do it myself with a dirty and quick job, would it be enough to change
subs.save(tempoutputfile, format_="srt") to subs.save(tempoutputfile, format_="ass")

and edit the ssastyle.py as my liking?

**Comment by bkiziuk** [comment]
There are probably going to be some more changes to subtitle handling in Kodi 20. I still don't want to mess with it ;-)
